name: 'IaC - Gerenciar Infraestrutura da Aplicação'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação a executar (apply ou destroy)'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
  # ATENÇÃO: Esta variável agora deve apontar para o repositório da aplicação principal,
  # pois este pipeline está no repositório de infra. Ex: 'BauerKayke/OficinaPro-KaykeBauer'
  TF_VAR_github_repo: "BauerKayke/OficinaPro-KaykeBauer"
  TF_VAR_github_token: ${{ secrets.GH_TOKEN }}

jobs:
  manage-app-infrastructure:
    name: 'Infra da Aplicação ${{ github.event.inputs.action }}'
    runs-on: ubuntu-latest
    defaults:
      run: { shell: bash, working-directory: ./app-infra } # <-- CAMINHO ATUALIZADO
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Ação do Terraform'
        run: terraform ${{ github.event.inputs.action }} -auto-approve
